name: Temporary Windows RDP VPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Configure RDP & Disable NLA
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # Admin User Password
          $AdminUser = [adsi]"WinNT://./runneradmin,user"
          $AdminUser.SetPassword("P@ssword12345")
          $AdminUser.SetInfo()

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.70.0

      - name: Display Connection Info
        shell: powershell
        run: |
          Start-Sleep -Seconds 5
          $ip = (tailscale ip -4)
          Write-Host "==========================================" -ForegroundColor Green
          Write-Host "Tailscale IP : $ip" -ForegroundColor Yellow
          Write-Host "Username     : runneradmin" -ForegroundColor Yellow
          Write-Host "Password     : P@ssword12345" -ForegroundColor Yellow
          Write-Host "==========================================" -ForegroundColor Green

      - name: Keep Alive
        shell: powershell
        run: |
          $i = 0
          while ($i -lt 360) {
            Start-Sleep -Seconds 60
            $i++
          }
